### ISSUE TITLE
Problem: Please call init before trying to purchase products.

### ISSUE THREAD

**Issue by arash9900** [coronalabs/plugins-source-google-iap-v3#2]
Hi,
Is this project ready to test or should i insert my own key?because i got above message in logcat and also store.isActive returns false
I also saw below link but i am logged in my gmail account in testing device: https://forums.coronalabs.com/topic/52042-is-it-possible-to-fail-elegantly-for-android-iap-when-not-logged-in/
Thanks

**Comment by amccaleb** [comment]
Hi ataafarin,

The Corona sample included with this project isn't ready to test out of the box. You'll need to follow our setup procedure at: https://docs.coronalabs.com/daily/guide/monetization/IAP/index.html#setupandroid.

When you try to build this project in your dev environment, be sure all this info from your AndroidManifest.xml is consistent with the info you entered in Google Play Dev Console.
Package Name
Version Name
Version Code

Furthermore, be sure you use the same keystore to sign your app as you entered in Google Pay Dev Console.

Failing to match any of that data means that communication to Google's In-App Billing will not work.

As for the gmail account, you'll need to be logged in to one of the test accounts you set up in Google Play Dev Console for your app. Any old gmail account won't work. Furthermore, using your developer gmail account (the one you used to sign in to Google Play Dev Console) also won't work.
